package com.cancer.therapy.evolution.core.model;

import java.sql.Date;
import java.util.Collection;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "users")
public class User {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// The user's email
	@NotNull
	private String email;

	// The user's name
	@NotNull
	private String name;

	@NotNull

	private String lastname;

	@NotNull
	private Date date;

	private String adress;

	@NotNull
	private String password;

	@JoinTable(name = "user_has_test")
	@ManyToMany(targetEntity = TestUser.class, fetch = FetchType.LAZY)
	private Collection<TestUser> testuser;

	// @JoinTable(name = "user_has_test")
	// @OneToMany(targetEntity = TestUser.class, fetch = FetchType.LAZY)

	// @ManyToMany(mappedBy="user",fetch=FetchType.LAZY)
	// private Collection<Account> Accounts;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	///// pour cree user //

	public User(String email, String password) {
		this.email = email;
		this.password = name;

	}

	/// constroctor with parameter ///

	public User(long id, String email, String name, String lastname, Date date, String adress, String password) {
		super();
		this.id = id;
		this.email = email;
		this.name = name;
		this.lastname = lastname;
		this.date = date;
		this.adress = adress;
		this.password = password;

	}
	// Getter and setter methods

	public long getId() {
		return id;
	}

	public void setId(long value) {
		this.id = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

}