# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

spring:
  datasource:
   url: jdbc:mysql://localhost:3306/theraby?createDatabaseIfNotExist=true
   username: therapy
   password: password
   testWhileIdle: true
   validationQuery: SELECT 1
  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
     naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     dialect: org.hibernate.dialect.MySQL5Dialect

server:
  contextPath: /cte
  port: 7998